import { defaultSchema, type Options } from "rehype-sanitize"

const globalAttributes = [
  ...(defaultSchema.attributes?.["*"] ?? []),
  "className",
  "ariaLabel",
  "ariaLabelledBy",
  "ariaDescribedBy",
  "role",
]

export const markdownSanitizeSchema: Options = {
  ...defaultSchema,
  tagNames: [
    ...(defaultSchema.tagNames ?? []),
    "iframe",
    "figure",
    "figcaption",
    "picture",
    "video",
    "audio",
    "source",
    "mark",
    "kbd",
    "samp",
  ],
  attributes: {
    ...defaultSchema.attributes,
    "*": globalAttributes,
    a: [...(defaultSchema.attributes?.a ?? []), "target", "rel"],
    div: [...(defaultSchema.attributes?.div ?? []), "className"],
    details: [...(defaultSchema.attributes?.details ?? []), "open", "className"],
    summary: [...(defaultSchema.attributes?.summary ?? []), "className"],
    figure: ["className"],
    figcaption: ["className"],
    iframe: [
      "src",
      "title",
      "width",
      "height",
      "allow",
      "allowFullScreen",
      "loading",
      "referrerPolicy",
      "sandbox",
      "className",
    ],
    img: [
      ...(defaultSchema.attributes?.img ?? []),
      "alt",
      "title",
      "width",
      "height",
      "loading",
      "decoding",
      "className",
      "dataSource",
    ],
    p: [...(defaultSchema.attributes?.p ?? []), "className"],
    span: [...(defaultSchema.attributes?.span ?? []), "className"],
    table: [...(defaultSchema.attributes?.table ?? []), "className"],
    th: [...(defaultSchema.attributes?.th ?? []), "className"],
    td: [...(defaultSchema.attributes?.td ?? []), "className"],
    video: ["src", "controls", "poster", "width", "height", "className"],
    audio: ["src", "controls", "className"],
    source: [...(defaultSchema.attributes?.source ?? []), "src", "type"],
  },
  protocols: {
    ...defaultSchema.protocols,
    src: ["http", "https"],
    href: ["http", "https", "mailto", "xmpp", "irc", "ircs"],
  },
}
